# Generated by Django 6.0.5 on 2026-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detail_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='favorites',
            field=models.CharField(default='', max_length=200),
        ),
    ]
