# Generated by Django 6.0.5 on 2026-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detail_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='favorites',
        ),
        migrations.AddField(
            model_name='detail',
            name='detail',
            field=models.JSONField(default=dict),
        ),
    ]
