# Generated by Django 6.0.5 on 2026-06-10 14:04

from django.db import migrations

def create_bakugo_details(apps, schema_editor):
    Detail = apps.get_model('blog', 'Detail')
    
    if Detail.objects.exists():
        return
    
    Detail.objects.create(detail={
        'name': 'Bakugo Katsuki',
        'hero_name': 'Great Explosion Murder God Dynamight (Daibaku Kisshin Dainamaito)',
        'age': '25 (post timeskip)',
        'quirk': 'Explosion',
        'birthday': 'April 20',
        'birthplace': 'near Shizuoka Prefecture',
        'manga/anime': 'My Hero Academia (Boku no Hiro Akademia)',
        'author/creator': 'Kohei Horikoshi',
        'role': 'Supporting character (Deuteragonist)',
        'occupation': 'Pro Hero',
        'Mother': 'Bakugo Mitsuki',
        'Father': 'Bakugo Masaru',
        'Blood Type': 'A',
        'Japanese VA': 'Nobuhiko Okamoto',
        'English VA': 'Clifford Chapin',
        'fighting_style': 'close-ranged combat',
        'education': ['Aldera Junior High', 'U.A. High School'],
        'appearance': ['lean muscular build', 'sharp intense bright red eyes', 'short, spiky, ash blond hair with choppy bangs'],
        'favorite_things': ['all spicy food', 'mountain climbing']
    })
    
    print("Bakugo details successfully added!")
    
def reverse_migration(apps, schema_editor):
    Detail = apps.get_model('blog', 'Detail')
    Detail.objects.all().delete()
    print("Bakugo details removed!")

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_bakugo_details, reverse_migration),
    ]
